Examination1/Examination/Controllers/TextController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Model;
using BLL;
using Webdiyer.WebControls.Mvc;
using System.IO;
using System.Data.SqlClient;
using System.Data;
using System.Web.Security;
using System.Data.OleDb;
using System.Transactions;
namespace Examination.Controllers
{
    public class TextController : Controller
    {
        //
        // GET: /Text/
        /// <summary>
        /// 实例化
        /// </summary>
        TextBLL textbll = new TextBLL();
        Function fun = new Function();
		CompanyBLL bll = new CompanyBLL();
		string ExcelName;
        /// <summary>
        /// 考试题显示
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Index(string name)
        {

            List<TextModel> list = textbll.ShowText(name);
            Session["cid"] = list[0].CompanyId;
            return View(list);
        }
		/// <summary>
		/// 所有公司
		/// </summary>
		/// <param name="pageindex"></param>
		/// <returns></returns>

		public ActionResult Allcompany(int pageindex = 1)
		{
			
			int pagesize = 8;
			PagedList<CompanyModel> list = bll.ShowCompany().ToPagedList(pageindex, pagesize);

			return View(list);
		}

        /// <summary>
        /// 表导入数据库
        /// </summary>
        /// <param name="filebase"></param>
        /// <param name="id"></param>
        /// <returns></returns>
        public ActionResult Show()
        {
			ViewBag.CompanyId = new SelectList(bll.ShowCompany(), "CompanyId", "CompanyName");
			return PartialView();
        }
        [HttpPost]

		public ActionResult Show(HttpPostedFileBase filebase, int CompanyId)
        {
            HttpPostedFileBase file = Request.Files["files"];
            string FileName;
            string savePath;
            if (file == null || file.ContentLength <= 0)
            {
                ViewBag.error = "文件不能为空";
                return View();
            }
            else
            {
                string filename = Path.GetFileName(file.FileName);
                int filesize = file.ContentLength;//获取上传文件的大小单位为字节byte
                string fileEx = System.IO.Path.GetExtension(filename);//获取上传文件的扩展名
                string NoFileName = System.IO.Path.GetFileNameWithoutExtension(filename);//获取无扩展名的文件名
                int Maxsize = 4000 * 1024;//定义上传文件的最大空间大小为4M
                string FileType = ".xls,.xlsx";//定义上传文件的类型字符串

                FileName = NoFileName + DateTime.Now.ToString("yyyyMMddhhmmss") + fileEx;
				CompanyModel model = fun.CompanyModel.Find(CompanyId);
				ExcelName =model.CompanyName+"-" + FileName;
                if (!FileType.Contains(fileEx))
                {
                    ViewBag.error = "文件类型不对，只能导入xls和xlsx格式的文件";
                    return View();
                }
                if (filesize >= Maxsize)
                {
                    ViewBag.error = "上传文件超过4M，不能上传";
                    return View();
                }
                string path = AppDomain.CurrentDomain.BaseDirectory + "Excel/";
                savePath = Path.Combine(path, FileName);
                file.SaveAs(savePath);
            }

            //string result = string.Empty;
            string strConn;
            strConn = "Provider=Microsoft.Ace.OleDb.12.0;" + "data source=" + savePath + ";Extended Properties='Excel 12.0; HDR=Yes; IMEX=1'";
            OleDbConnection conn = new OleDbConnection(strConn);
            conn.Open();
            OleDbDataAdapter myCommand = new OleDbDataAdapter("select * from [Sheet1$]", strConn);
            DataSet myDataSet = new DataSet();
            try
            {
                myCommand.Fill(myDataSet, "ExcelInfo");
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View();
            }
            DataTable table = myDataSet.Tables["ExcelInfo"].DefaultView.ToTable();

            //引用事务机制，出错时，事物回滚
            using (TransactionScope transaction = new TransactionScope())
            {
                for (int i = 0; i < table.Rows.Count; i++)
                {
                    
                    TextModel model = new TextModel();
                  
                    model.TName = table.Rows[i][0].ToString();
                    model.TAnswer = table.Rows[i][1].ToString();
					model.CompanyId = CompanyId;
					model.ExcelName = ExcelName;
                   fun.TextModel.Add(model);
                    fun.SaveChanges();
                }
                transaction.Complete();
            }
            ViewBag.error = "导入成功";
            System.Threading.Thread.Sleep(2000);
            return Content("<script>alert('数据导入成功！');location.href='/Text/Show'</script>");
        }




       /// <summary>
       /// 数据库导出
       /// </summary>
       /// <param name="strGUID"></param>
       /// <returns></returns>

        public ActionResult DataTableToExcel()
        {

            return View();
        }
        [HttpPost]
        public ActionResult DataTableToExcel(string strGUID)
        {
			if(strGUID =="")
			{

				return Content("<script>alert('至少选择一项');location.href='/Text/Index/" + Session["cid"] + "'</script>");
			}
		else
	{
		string[] GUID = Request.Form["strGUID"].Split(',');



		//这个是读取要导出的列表，逻辑要自己写的
		DataTable dt = new DataTable();
		dt.Columns.Add("序号");
		dt.Columns.Add("题目");
		dt.Columns.Add("答案");
		foreach (var aa in GUID)
		{
			if (aa != null && aa != "")
			{
				int id = Convert.ToInt32(aa);
				//List<User> list = db.user.Where(p => p.Uid == id).ToList();
				TextModel model = fun.TextModel.Find(id);
				dt.Rows.Add(model.Tid, model.TName, model.TAnswer);
			}
		}




		System.Web.UI.WebControls.DataGrid dgExport = null;

		// 当前对话 

		System.Web.HttpContext curContext = System.Web.HttpContext.Current;

		// IO用于导出并返回excel文件 

		System.IO.StringWriter strWriter = null;

		System.Web.UI.HtmlTextWriter htmlWriter = null;

		string filename = DateTime.Now.Year + "_" + DateTime.Now.Month + "_" + DateTime.Now.Day + "_"

		+ DateTime.Now.Hour + "_" + DateTime.Now.Minute;

		byte[] str = null;



		if (dt != null)
		{

			// 设置编码和附件格式

			curContext.Response.Charset = "GB2312";

			Response.AppendHeader("Content-Disposition", "attachment;filename=" + filename + ".xls");

			curContext.Response.ContentEncoding = System.Text.Encoding.GetEncoding("GB2312");//设置输出流为简体中文

			curContext.Response.ContentType = "application/vnd.ms-excel";

			//System.Text.Encoding.UTF8;

			// 导出excel文件 

			strWriter = new System.IO.StringWriter();

			htmlWriter = new System.Web.UI.HtmlTextWriter(strWriter);



			//// 为了解决dgData中可能进行了分页的情况，需要重新定义一个无分页的DataGrid 

			dgExport = new System.Web.UI.WebControls.DataGrid();

			dgExport.DataSource = dt.DefaultView;

			dgExport.AllowPaging = false;

			dgExport.DataBind();

			dgExport.RenderControl(htmlWriter);

			// 返回客户端 

			str = System.Text.Encoding.UTF8.GetBytes(strWriter.ToString());

		}

		return File(str, "attachment;filename=" + filename + ".xls");

	}
	}
		/// <summary>
		/// 查询
		/// </summary>
		/// <param name="CompanyName"></param>
		/// <param name="index"></param>
		/// <returns></returns>
		[HttpGet]


		public ActionResult SrechCompany(string CompanyName, int index = 1)
		{
			int size = 8;
			PagedList<CompanyModel> list = bll.SreachCompany(CompanyName).ToPagedList(index, size);
			return View("AllCompany", list);

		}
        /// <summary>
        /// 显示所有试题的试卷
        /// </summary>
        /// <returns></returns>
        public ActionResult ShowExcelName(int id)
        {
            Session["Cids"] = id;
            return View();
        }
    }
}

Examination1/Examination/Views/Text/Allcompany.cshtml
@model PagedList<Model.CompanyModel>
@using Webdiyer.WebControls.Mvc;

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Allcompany</title>
</head>
<body>

    <div class="container hbox">

        <h3 class="text-center">各大知名企业</h3>

        <div class="text-center">
            @using (Html.BeginForm("SrechCompany", "Text", FormMethod.Get))
            {

                <label>根据公司名称查找：</label>@Html.TextBox("CompanyName")
                <input type="submit" value="查询" />


            }



        </div>
        <div class="row">
            @foreach (var item in Model)
            {


                <div class="col-md-3 col-sm-6 highlight">
                    <div>
                        <div class="h-body text-center">
                            <h4><i><a title="公司介绍： @item.CompanyRemark2" href="#"><img src="@item.Companylog" width="80" height="80" /></a></i></h4>
                        </div>
                        <div class="h-body text-center">
                            <h4>@item.CompanyName</h4>
                        </div>
                        <div class="h-body text-center">
                            <a href="/Text/ShowExcelName/@item.CompanyId">点击查看面试题</a>
                          
                        </div>
                    </div>
                </div>
            }
        </div>
        <br />
        <br />
        <div class="container text-center">
            @Html.Pager(Model, new PagerOptions { PageIndexParameterName = "pageindex" })

        </div>
        <br />
        <br />
        <br />
        <br />

        <!-- /row  -->



    </div>
    <footer id="footer" class="navbar-fixed-bottom">

        <div class="footer1">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 panel">
                        <h3 class="panel-title">要努力</h3>
                        <div class="panel-body">
                            <p>在别人肆意说你的时候，问问自己，到底怕不怕，输不输的起。不必害怕，不要后退，不须犹豫，难过的时候就一个人去看看这世界。多问问自己，你是不是已经为了梦想而竭尽全力了？</p>
                        </div>
                    </div>

                    <div class="col-md-4 panel contact">
                        <h3 class="panel-title">
                            座右铭
                        </h3>
                        <div class="panel-body">
                            <p>
                                天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为。
                                ——《孟子?告子下》
                            </p>

                        </div>
                    </div>

                    @*<div class="col-md-3 panel">    以后可以扩展留言板
                            <h3 class="panel-title">Follow me</h3>
                            <div class="panel-body">
                                <p class="follow-me-icons">
                                    <a href=""><i class="fa fa-twitter fa-2"></i></a>
                                    <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                                    <a href=""><i class="fa fa-github fa-2"></i></a>
                                    <a href=""><i class="fa fa-facebook fa-2"></i></a>
                                    <a href=""><i class="fa fa-youtube fa-2"></i></a>
                                    <a href=""><i class="fa fa-pinterest fa-2"></i></a>
                                </p>
                            </div>
                        </div>*@

                </div>
                <!-- /row of panels -->
            </div>
        </div>

        <div class="footer2">
            <div class="container">
                <div class="row">

                    <div class="col-sm-6 panel">
                        <div class="panel-body">
                            <p class="text-right">
                                Copyright &copy; 2016.面试题库 All rights reserved.
                            </p>
                        </div>
                    </div>

                </div>
                <!-- /row of panels -->
            </div>
        </div>

    </footer>
</body>
</html>

Examination1/Examination/Views/Text/Index.cshtml
@model List<Model.TextModel>

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <style type="text/css">
      #gotop {
            display: none;
            width: 55px;
             height: 55px;
             position: fixed;
             right: 50px;
             bottom: 50px;
           background: url(img/1.png) no-repeat -70px 0px;
        }
    </style>

</head>
<body>

    <div class="container">
        <div class="row">
            <header class="page-header">
                <h1 class="page-title">答题卡</h1>

            </header>
            @using (Html.BeginForm("DataTableToExcel", "Text", FormMethod.Post))
            {
                <table>
                    <tr><td></td></tr>
                    <tr>
                        <td>@Html.Hidden("strGUID")</td>
                        <td>
                            <input id="Button1" type="button" value="全选" />&nbsp;&nbsp;
                            &nbsp;&nbsp;<input type="submit" value="导出" onclick="selectExcel()" />
                        </td>
                    </tr>
                </table>
            }

            @foreach (var item in Model)
            {
                <!-- Article main content -->
                <article class="col-sm-9 maincontent">


                    <p>
                        <input type="checkbox" name="check" id="ck" value="@item.Tid" /> @item.TName
                    </p>
                    <br>
                    <!--NOTE: Update your email Id in "contact_me.php" file in order to receive emails from your contact form-->
                   



                        <div class="control-group">
                            <div class="controls">
                                <textarea rows="10" cols="100" class="form-control"
                                          placeholder="请输入您的答案" id="message" required
                                          data-validation-required-message="Please enter your message" 
                                          data-validation-minlength-message="Min 5 characters"
                                          maxlength="999" style="resize:none"></textarea>
                            </div>
                        </div>
                        <div id="success"> </div> <!-- For success/fail messages -->

                   

                </article>
            }
            <!-- /Article -->


        </div>
        <br />

        <div class="col-sm-9 maincontent">
            <button type="button" class="btn btn-primary pull-right" onclick="sub()">提交</button>
        </div>
    </div>
    <div id="h" hidden="hidden" class="container">

        @foreach (var item in Model)
        {

            <label style="color:red">题目</label> @item.TName <br />
            <label style="color:red">答案</label> @item.TAnswer<br /><br />
        }



    </div>
    
    <div id="gotop">
     <img src="~/img/5-1304121QA4.gif" />
    </div>
    <br />
    <br />

    <footer id="footer">

        <div class="footer1">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 panel">
                        <h3 class="panel-title">要努力</h3>
                        <div class="panel-body">
                            <p>在别人肆意说你的时候，问问自己，到底怕不怕，输不输的起。不必害怕，不要后退，不须犹豫，难过的时候就一个人去看看这世界。多问问自己，你是不是已经为了梦想而竭尽全力了？</p>
                        </div>
                    </div>

                    <div class="col-md-4 panel contact">
                        <h3 class="panel-title">
                            座右铭
                        </h3>
                        <div class="panel-body">
                            <p>
                                天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为。
                                ——《孟子?告子下》
                            </p>

                        </div>
                    </div>

                    @*<div class="col-md-3 panel">    以后可以扩展留言板
                            <h3 class="panel-title">Follow me</h3>
                            <div class="panel-body">
                                <p class="follow-me-icons">
                                    <a href=""><i class="fa fa-twitter fa-2"></i></a>
                                    <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                                    <a href=""><i class="fa fa-github fa-2"></i></a>
                                    <a href=""><i class="fa fa-facebook fa-2"></i></a>
                                    <a href=""><i class="fa fa-youtube fa-2"></i></a>
                                    <a href=""><i class="fa fa-pinterest fa-2"></i></a>
                                </p>
                            </div>
                        </div>*@

                </div>
                <!-- /row of panels -->
            </div>
        </div>

        <div class="footer2">
            <div class="container">
                <div class="row">

                    <div class="col-sm-6 panel">
                        <div class="panel-body">
                            <p class="text-right">
                                Copyright &copy; 2016.面试题库 All rights reserved.</a>
                            </p>
                        </div>
                    </div>

                </div>
                <!-- /row of panels -->
            </div>
        </div>

    </footer>










</body>

</html>

<script src="~/Scripts/jquery-1.8.2.min.js"></script>



<script type="text/javascript" language="javascript">
    function sub() {
        if ($("#message").val() != "")
        {
            $("#h").show();
        }
        else
        {
            alert("请您把题答完！！！")
        }
       


    }
        $("#Button1").click(function () {
            $(":checkbox").each(function(){
            $(this).attr("checked",!$(this).attr("checked"))
            
            })

        })
        function selectExcel() {
           
            var GUID = document.getElementsByName("check");

            var temp = "";

            var strGUID = "";

            for (var i = 0; i < GUID.length; i++) {

                if (GUID[i].checked) {

                    temp += GUID[i].value + ",";

                }

            }
            strGUID = temp


            //alert(strGUID);//测试取到的值是否正确
           
            //$("#GUID").val(strGUID);//将多选的值赋给Id为strGUID的隐藏域
            document.getElementById("strGUID").value = strGUID;
           
        }
      

</script>
<script type="text/javascript">

     function goTop() {
  
         $(window).scroll(function (e) {
      
                 //若滚动条离顶部大于100元素
       
                   if ($(window).scrollTop() > 100)
           
                         $("#gotop").fadeIn(1000);//以1秒的间隔渐显id=gotop的元素
           
                      else
            
                       $("#gotop").fadeOut(1000);//以1秒的间隔渐隐id=gotop的元素
          
               });
      
          };
    
     $(function () {
       
           //点击回到顶部的元素
       
            $("#gotop").click(function (e) {
         
                   //以1秒的间隔返回顶部
          
                  $('body,html').animate({ scrollTop: 0 }, 1000);
         
              });
    
            $("#gotop").mouseover(function (e) {
          
                    $(this).css("background", "url(~/img/1.png) no-repeat 0px 0px");
       
               });
       
               $("#gotop").mouseout(function (e) {
     
                  $(this).css("background", "url(img/1.png) no-repeat -70px 0px");
  
             });
   
          goTop();//实现回到顶部元素的渐显与渐隐
   
    });

</script>




Examination1/Examination/Views/Text/Show.cshtml
@model Model.TextModel

@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="zh">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <title>导入面试题</title>
    <link rel="stylesheet" media="screen" href="http://fonts.useso.com/css?family=Open+Sans:300,400,700">
    <link href="~/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
   
    <link href="~/assets/css/font-awesome.min.css" rel="stylesheet" />
    <!-- Custom styles for our template -->
    <link href="~/assets/css/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/assets/css/da-slider.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
</head>
<body>
    <div class="navbar navbar-inverse">
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                <a class="navbar-brand" href="/Home/Index">

                    <img src="~/assets/images/favicon.png" />面试题库
                </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav pull-right" style="margin-right:600px">
                    <li class="active"><a href="/Home/Addcompany">添加公司</a></li>
                    <li></li>
                    <li class="active"><a href="/Text/Show">导入面试题</a></li>
                </ul>
            </div>
            <!--/.nav-collapse -->
        </div>
    </div>
    <div style="padding-left:450px;padding-top:50px;">
        @using (Html.BeginForm("Show", "Text", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <p>
                <img src="~/UpLoadFile/Excel样式模板.png" style="width:500px;height:200px;" />
                <h3>选择文件：</h3> 
                  <br />
                <input id="FileUpload" type="file" name="files" style="width: 250px; height: 24px; background: White" class="easyui-validatebox file" />
            </p>
            <p>
                <h3> 公司:</h3><br />
                 @Html.DropDownList("CompanyId")
            </p>
            <p style="padding-top:20px;">
                <button type="submit" class="btn btn-primary">导入</button>
                <button type="reset" class="btn btn-default">取消</button>
            </p>
        }
    </div>
   
   
    <script src="~/assets/js/modernizr-latest.js"></script>
    <script src="http://apps.bdimg.com/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://apps.bdimg.com/libs/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <script src="~/assets/js/jquery.cslider.js"></script>
    <script src="~/assets/js/custom.js"></script>
</body>
</html>

Examination1/Examination/Views/Text/ShowExcelName.cshtml
@model List<Model.TextModel>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowExcelName</title>
</head>
<body>
    <div style="height:500px;margin-top:100px" >
        <h1 style="color:blue;" class="text-center">题库 @ViewBag.count</h1>
        <div style="padding-left:250px;padding-top:20px;">
            <table class="text-center">
                @{
                    BLL.TextBLL bll = new BLL.TextBLL();
                    if (Convert.ToInt32(@Session["Cids"]) != 0)
                    {

                        foreach (var item in bll.GetExamExcal(Convert.ToInt32(@Session["Cids"])))
                        {
                            <tr><td style="font-size:20px;"><a href="/Text/Index/?name=@item.Key">@item.Key</a></td></tr>
                            <tr style="padding-top:10px;"><td>@(bll.GetCompanyName(Convert.ToInt32(item.Value)))</td></tr>
                        }
                    }
                    else
                    {

                        foreach (var item in bll.GetExamExcal(Convert.ToInt32(@Session["Cids"])))
                        {
                            <tr><td style="font-size:20px;"><a href="/Text/Index/?name=@item.Key">@item.Key</a></td></tr>
                            <tr style="padding-top:10px;"><td>@(bll.GetCompanyName(Convert.ToInt32(item.Value)))</td></tr>
                        }
                    }
                }
            </table>
        </div>
    </div>
    <footer id="footer">

        <div class="footer1">
            <div class="container">
                <div class="row">
                    <div class="col-md-5 panel">
                        <h3 class="panel-title">要努力</h3>
                        <div class="panel-body">
                            <p>在别人肆意说你的时候，问问自己，到底怕不怕，输不输的起。不必害怕，不要后退，不须犹豫，难过的时候就一个人去看看这世界。多问问自己，你是不是已经为了梦想而竭尽全力了？</p>
                        </div>
                    </div>

                    <div class="col-md-4 panel contact">
                        <h3 class="panel-title">
                            座右铭
                        </h3>
                        <div class="panel-body">
                            <p>
                                天将降大任于是人也，必先苦其心志，劳其筋骨，饿其体肤，空乏其身，行拂乱其所为。
                                ——《孟子?告子下》
                            </p>

                        </div>
                    </div>

                    @*<div class="col-md-3 panel">    以后可以扩展留言板
                            <h3 class="panel-title">Follow me</h3>
                            <div class="panel-body">
                                <p class="follow-me-icons">
                                    <a href=""><i class="fa fa-twitter fa-2"></i></a>
                                    <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                                    <a href=""><i class="fa fa-github fa-2"></i></a>
                                    <a href=""><i class="fa fa-facebook fa-2"></i></a>
                                    <a href=""><i class="fa fa-youtube fa-2"></i></a>
                                    <a href=""><i class="fa fa-pinterest fa-2"></i></a>
                                </p>
                            </div>
                        </div>*@

                </div>
                <!-- /row of panels -->
            </div>
        </div>

        <div class="footer2">
            <div class="container">
                <div class="row">

                    <div class="col-sm-6 panel">
                        <div class="panel-body">
                            <p class="text-right">
                                Copyright &copy; <a href="/Areas/Admin/Index">2016.面试题库</a> All rights reserved.
                            </p>
                        </div>
                    </div>

                </div>
                <!-- /row of panels -->
            </div>
        </div>

    </footer>
</body>
</html>